---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - task.hemmelig.io
  resources:
  - notifies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.hemmelig.io
  resources:
  - notifies/finalizers
  verbs:
  - update
- apiGroups:
  - task.hemmelig.io
  resources:
  - notifies/status
  verbs:
  - get
  - patch
  - update
